version: '3'
services:
  # geo-postgres-compose:
  #   container_name: 'geo-postgres-compose'
  #   image: geographica/postgis:dev_diplodocus
  #   environment:
  #     - POSTGRES_PASSWD=postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ${LOCAL_DATABASE}:/data
  #     - ./data:/data_import 
  #   networks:
  #     - geo-postgres-compose-network
  # THIS IS THE CONNEXION WITH GOOGLE SQL INSTANCE
  # geo-postgres-compose:
  #   container_name: "geo-postgres-compose"
  #   image: gcr.io/cloudsql-docker/gce-proxy:1.16
  #   # Port: MySQL (3306), PostgreSQL (5433)
  #   command: /cloud_sql_proxy -instances=skydipper-196010:europe-west1:skydipper-pg-1=tcp:0.0.0.0:5433 -credential_file=/config
  #   volumes:
  #     - ./sqlPrivateKey.json:/config
  #   ports:
  #     - "5434:5433"
  #   networks:
  #     - geo-postgres-compose-network
  #   restart: always

  deepsky:
    env_file: 
      - .env
    build: .
    ports:
      - 8888:8888
    networks:
      - geopredictordb-network
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
  
    volumes: 
      - .:/tf/deepsky
networks: 
  geopredictordb-network:
    driver: bridge
